
name: batch-env

channels:
- conda-forge

dependencies:
- conda-forge::pandas=1.0.1
- conda-forge::tabulate=0.8.7
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.0
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::jupyter_contrib_nbextensions=0.5.1
- conda-forge::matplotlib=3.1.3
- conda-forge::plotnine=0.6.0
- conda-forge::rdkit=2019.09.3
- conda-forge::nb_black=1.0.7
- conda-forge::r-base=3.5.1
- conda-forge::r-knitr=1.22
- conda-forge::r-rmarkdown=1.12
- conda-forge::r-tidyverse=1.3.0

- conda-forge::r-essentials
- conda-forge::jupyterlab=2.2.0
- conda-forge::pip=20.1.1
- conda-forge::r-reticulate=1.10
- conda-forge::scikit-learn

- pip:
  - git+https://github.com/cytomining/pycytominer@dd064c2185435e19541bafa7c976d55da15cf09e
